/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[UserGroupId]
      ,[UserName]
      ,[Password]
      ,[FirstName]
      ,[LastName]
      ,[Email]
      ,[ResetPasswordCode]
      ,[Address]
      ,[CreatedOn]
      ,[CreatedBy]
      ,[ModifiedOn]
      ,[ModifiedBy]
      ,[IsDeleted]
  FROM [LaptopShopOnline001].[dbo].[User]
 ORDER BY [UserGroupId]