USE [LaptopShopOnline001]
GO

INSERT INTO [dbo].[Credential] ([UserGroupId],[RoleId]) VALUES (N'MANAGER_DEFAULT', N'MANAGER_ROLE_SYS_CREATE')
INSERT INTO [dbo].[Credential] ([UserGroupId],[RoleId]) VALUES (N'MANAGER_DEFAULT', N'MANAGER_ROLE_SYS_UPDATE')
INSERT INTO [dbo].[Credential] ([UserGroupId],[RoleId]) VALUES (N'MANAGER_DEFAULT', N'MANAGER_ROLE_SYS_DELETE')
INSERT INTO [dbo].[Credential] ([UserGroupId],[RoleId]) VALUES (N'MANAGER_DEFAULT', N'MANAGER_ROLE_SYS_READ')
GO


